package types

import (
	"errors"

	sdk "github.com/cosmos/cosmos-sdk/types"
)

// -------------------------
// Expected keeper interfaces
// -------------------------

type OracleKeeper interface {
	GetPrice(ctx sdk.Context, marketID string) (sdk.Dec, int64, error)
}

type FundingKeeper interface {
	GetCumulativeFunding(ctx sdk.Context, marketID string, addr string) (sdk.Dec, error)
}

type PositionKeeper interface {
	GetPositions(ctx sdk.Context, addr string) []Position
	ReducePosition(ctx sdk.Context, addr string, marketID string, reduceBy sdk.Dec) error
}

type SettlementKeeper interface {
	ExecuteTrade(ctx sdk.Context, addr string, marketID string, size sdk.Dec, price sdk.Dec) error
}

// -------------------------
// Params
// -------------------------

type Params struct {
	InitialMarginRatio     sdk.Dec `json:"imr"`
	MaintenanceMarginRatio sdk.Dec `json:"mmr"`
	LiquidationPenaltyMin  sdk.Dec `json:"penalty_min"`
	PartialLiquidationRate sdk.Dec `json:"partial_liq_rate"`
}

func DefaultParams() Params {
	return Params{
		InitialMarginRatio:     sdk.MustNewDecFromStr("0.05"),  // 5% IMR → 20x max leverage
		MaintenanceMarginRatio: sdk.MustNewDecFromStr("0.03"),  // 3% MMR
		LiquidationPenaltyMin:  sdk.MustNewDecFromStr("0.02"),  // 2% penalty
		PartialLiquidationRate: sdk.MustNewDecFromStr("0.50"),  // reduce 50% on liquidation
	}
}

// -------------------------
// State types
// -------------------------

// Account holds cross-margin state for a single user.
// Proto-generated in production; defined here for keeper use.
type Account struct {
	Address       string  `json:"address"`
	Collateral    sdk.Dec `json:"collateral"`
	UnrealizedPnL sdk.Dec `json:"unrealized_pnl"`
	FundingPnL    sdk.Dec `json:"funding_pnl"`
	MarginUsed    sdk.Dec `json:"margin_used"`
}

// Required to satisfy codec.ProtoMarshaler (stub; replace with protogen output)
func (a *Account) Reset()         {}
func (a *Account) String() string { return a.Address }
func (a *Account) ProtoMessage()  {}

func (a *Account) Marshal() ([]byte, error) {
	// In production this is generated by protoc. Stub for compilation.
	return []byte{}, nil
}

func (a *Account) Unmarshal(bz []byte) error {
	return nil
}

// Position mirrors the proto-generated type from x/position.
// Duplicated here to avoid circular imports; x/margin/types must not import x/position/types.
type Position struct {
	MarketID   string
	Size       sdk.Dec
	EntryPrice sdk.Dec
}

// MarginRisk is the computed risk snapshot returned by queries.
type MarginRisk struct {
	Equity      sdk.Dec
	IMR         sdk.Dec
	MMR         sdk.Dec
	HealthRatio sdk.Dec
	IsLiquidatable bool
}

// -------------------------
// Errors
// -------------------------

var (
	ErrInvalidAmount           = errors.New("amount must be positive")
	ErrInsufficientCollateral  = errors.New("insufficient collateral")
	ErrWithdrawalBreachesMargin = errors.New("withdrawal would breach maintenance margin")
	ErrAccountNotFound         = errors.New("margin account not found")
	ErrBelowMaintenanceMargin  = errors.New("account below maintenance margin")
)